### ISSUE TITLE
Header components - mobile

### ISSUE THREAD

**Issue by jacekelgda** [x-team/unleash-styles#15]
We need to figure out what will be the best way to implement mobile css.
In styleguides provided by @agiannastasio mobile styles are in separate files. I am not sure if we can keep that approach using css modules. 

Please discuss first.

**Comment by jacekelgda** [comment]
<img width="493" alt="screen shot 2017-07-13 at 13 31 44" src="https://user-images.githubusercontent.com/1003372/28164439-ae77c3a0-67cf-11e7-9676-90abbb2bd027.png">

**Comment by jacekelgda** [comment]
<img width="504" alt="screen shot 2017-07-13 at 13 32 52" src="https://user-images.githubusercontent.com/1003372/28164472-d39bf494-67cf-11e7-88bb-d066270b4770.png">

**Comment by jacekelgda** [comment]
https://github.com/x-team/unleash/blob/styleguide-dev/styleguide/src/css/header__menu--mobile.css

https://github.com/x-team/unleash/blob/styleguide-dev/styleguide/src/css/header__user-menu.css

**Comment by agiannastasio** [comment]
We could merge the menu styles in one single file, no prob with that. The issue I think is the actual mobile menu, which I implemented in JS:
[https://github.com/x-team/unleash/blob/styleguide-dev/styleguide/src/js/mobile-menu.js](https://github.com/x-team/unleash/blob/styleguide-dev/styleguide/src/js/mobile-menu.js)

**Comment by jacekelgda** [comment]
Thanks for info @agiannastasio , I don't think it will be a problem to implement js logic in component.
