### ISSUE TITLE
Add Goal modal window

### ISSUE THREAD

**Issue by agiannastasio** [x-team/unleash-styles#18]
React component for the **Add Goal** section (modal window, form, red circle button)
![image](https://user-images.githubusercontent.com/584702/28908972-c8cfca30-77fc-11e7-887d-3edcd64d33ba.png)

**Comment by jacekelgda** [comment]
Awesome, thanks for creating issue for this @agiannastasio

**Comment by szymonmichalak** [comment]
Closing this in favour of #20, #21 , #22.
