### ISSUE TITLE
Testing rect components

### ISSUE THREAD

**Issue by jacekelgda** [x-team/unleash-styles#2]
Implement testing (any suggestions? karma + mocha + chai / jest / anything else?)

**Comment by jacekelgda** [comment]
I suggest Jest: https://facebook.github.io/jest/docs/tutorial-react.html

**Comment by nicksp** [comment]
Jets is a great tool, especially in combination with [Enzyme](http://airbnb.io/enzyme/). Here are some good resources to follow along: 

- https://medium.com/@kentcdodds/migrating-to-jest-881f75366e7e
- https://github.com/kentcdodds/react-jest-workshop / http://slides.com/kentcdodds/testing-react#/

**Comment by jacekelgda** [comment]
I don't see anyone suggesting any other tools - Jest it is.
