### ISSUE TITLE
Input component

### ISSUE THREAD

**Issue by szymonmichalak** [x-team/unleash-styles#21]
Input component:

![input](https://user-images.githubusercontent.com/6726839/28915342-1daf98a4-783f-11e7-94e8-44d7c7d97375.png)

**Props:**
- `type` - `text` / `textarea` / [etc.](https://developer.mozilla.org/en/docs/Web/HTML/Element/input#Form_%3Cinput%3E_types) - should just pass it to `<input type={this.props.type} ... />`
- `id` / `label` / `placeholder` and all the other standard input props - it should be enough to do `<input ... {...this.props} />`

**Comment by agiannastasio** [comment]
We might need a separate component for the `<textarea>` element, as `<input type="textarea">` is not valid.
